// const rightNames: string[] = [
//     "aristotle",
//     "bacon",
//     "chomsky",
//     "confucious",
//     "decartes",
//     "kant",
//     "nietzsche",
//     "plato",
//     "pythagoras",
//     "satre",
//     "socrates",
// ]

const rightNames: string[] = [
    "adams",
    "asimov",
    "baum",
    "bradbury",
    "bradley",
    "burgess",
    "card",
    "clark",
    "gaiman",
    "guin",
    "herbert",
    "howard",
    "huxley",
    "king",
    "lewis",
    "lovecraft",
    "loudon",
    "niven",
    "rice",
    "orwell",
    "shelley",
    "tolkein",
    "verne",
    "vogt",
    "vonnegut",
    "wells",
]

const leftNames: string[] = [
    "admiring",
    "adoring",
    "agitated",
    "angry",
    "backstabbing",
    "berserk",
    "boring",
    "clever",
    "cocky",
    "compassionate",
    "condescending",
    "cranky",
    "desperate",
    "determined",
    "distracted",
    "dreamy",
    "drunk",
    "ecstatic",
    "elated",
    "elegant",
    "evil",
    "fervent",
    "focused",
    "furious",
    "gloomy",
    "goofy",
    "grave",
    "happy",
    "high",
    "hopeful",
    "hungry",
    "insane",
    "jolly",
    "jovial",
    "kickass",
    "lonely",
    "loving",
    "mad",
    "modest",
    "naughty",
    "nostalgic",
    "pensive",
    "prickly",
    "reverent",
    "romantic",
    "sad",
    "serene",
    "sharp",
    "sick",
    "silly",
    "sleepy",
    "stoic",
    "stupefied",
    "suspicious",
    "tender",
    "thirsty",
    "trusting",
]

function picker(arr: string[]) {
    return arr[Math.floor(Math.random() * arr.length) + 1];
}

export function generateRandomName() {
    return picker(leftNames) + "-" + picker(rightNames);
}

export default generateRandomName;